[package]
name = "oblivious-transfer"
version = "0.1.0"
authors = ["Lennart Vogelsang <dev@vogelsangs.net>"]

[lib]
name = "ot"
path = "src/lib.rs"

[[bin]]
name = "ot_test_bin"
path = "src/bin.rs"

[dependencies]
curve25519-dalek = "^0.16"
rand = "0.4"
digest = "0.7.2"
sha3 = "0.7.3"
